import { makeStyles } from "@material-ui/styles";

export const useStyles = makeStyles((theme) => ({
  "@keyframes rotating": {
    "0%": {
      transform: "rotate(0)",
    },
    "100%": {
      transform: "rotate(359deg)",
    },
  },
  sectionTitle: {
    marginBottom: 8,
    fontSize: 15,
    color: "#969696",
  },
  uploadFrame: {
    position: "relative",
    border: "1px solid #dbebf5",
    background: "#fafdff",
    borderRadius: 5,
    cursor: "pointer",
    userSelect: "none",
    transition: "all 0.15s",
    overflow: "hidden",
    "&:hover": {
      borderColor: "#b0d6ef",
    },
    "&.has-focus": {
      background: "#f6fff4",
      borderColor: "#ace89c",
      boxShadow: "0 5px 50px 0 rgba(0,0,0,0.1) !important",
    },
  },
  uploadDefaultState: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    minHeight: 350,
    transition: "all 0.15s",
    "&.has-focus": {
      transform: "scale(0.8)",
      opacity: 0,
      visibility: "hidden",
    },
  },
  uploadFocusState: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    background: "#f6fff4",
    borderRadius: 10,
    transition: "all 0.15s",
    transform: "scale(1.2)",
    opacity: 0,
    visibility: "hidden",
    "&.has-focus": {
      transform: "none",
      opacity: 1,
      visibility: "visible",
    },
  },
  uploadIcon: {
    color: "#e9f1f7",
    fontSize: 100,
    "&.has-focus": {
      display: "none",
    },
  },
  uploadFocusIcon: {
    color: "#ace89c",
    fontSize: 140,
  },
  uploadFrameText: {
    margin: 10,
    fontSize: 16,
    textAlign: "center",
    color: "#9e9e9e",
  },
  uploadBrowse: {
    padding: 0,
    color: "#0277BD",
    background: "none",
    border: "none",
    borderBottom: "1px solid #0277BD",
    fontSize: 16,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.2s",
  },
  file: {
    display: "flex",
    alignItems: "center",
    padding: "10px 10px 10px 20px",
    borderRadius: 5,
    background: "#fff",
    border: "1px solid #efefef",
    boxShadow: "0 0 30px 0 rgba(0,0,0,0.03)",
  },
  fileUploaded: {
    background: "#f4fbf4",
    borderColor: "#f4fbf4",
    boxShadow: "none",
    marginBottom: 12,
  },
  fileIc: {
    marginRight: 5,
    fontSize: 18,
    color: "#0277BD",
  },
  fileName: {
    display: "flex",
    alignItems: "center",
    marginRight: "auto",
  },
  fileUploadError: {
    fontSize: 14,
  },
  fileUploadingWindow: {
    position: "fixed",
    flexDirection: "column",
    left: "50%",
    transform: "translateX(-50%)",
    maxWidth: "500px",
    zIndex: 1000,
    bottom: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "15px 20px",
    background: "#fff",
    border: "1px solid #e8e8e8",
    fontSize: 16,
    fontWeight: 800,
    borderRadius: 4,
    boxShadow: "0 0 50px 1px rgba(0,0,0,0.25)",
  },
  fileUploadingWindowHeader: {
    display: "flex",
    alignItems: "center",
  },
  fileUploadingWindowDesc: {
    fontSize: 16,
    fontWeight: 400,
    marginTop: 15,
  },
  fileUploading: {
    display: "inline-block",
    marginRight: 10,
    fontSize: 30,
    color: "#8BC34A",
    animation: `$rotating 0.8s infinite`,
  },
  fileUpload2: {
    display: "flex",
    alignItems: "center",
    padding: "0 15px",
    height: 38,
    marginLeft: 8,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 1,
    background: "#039BE5",
    color: theme.palette.white,
    borderRadius: 4,
    border: "none",
    transition: "all 0.2s",
    cursor: "pointer",
    "&:hover": {
      background: "#03A9F4",
    },
    "&[disabled]": {
      background: "#e7e7e7",
      color: "#999999",
      cursor: "default",
    },
  },
  fileUpload: {
    display: "flex",
    alignItems: "center",
    height: 28,
    padding: "0 15px",
    marginLeft: 8,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 1,
    background: "#039BE5",
    color: "#fff",
    borderRadius: 14,
    border: "none",
    transition: "all 0.2s",
    cursor: "pointer",
    "&:hover": {
      background: "#03A9F4",
    },
    "&[disabled]": {
      background: "#e7e7e7",
      color: "#999999",
      cursor: "default",
    },
  },
  fileUploadIc: {
    marginRight: 5,
    fontSize: 16,
  },
  fileOpen: {
    display: "flex",
    alignItems: "center",
    height: 28,
    padding: "0 15px",
    marginLeft: 8,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 1,
    background: "#43A047",
    color: theme.palette.white,
    borderRadius: 14,
    border: "none",
    transition: "all 0.2s",
    cursor: "pointer",
    "&:hover": {
      background: "#388E3C",
    },
  },
  fileOpenIc: {
    marginRight: 5,
    fontSize: 16,
  },
  fileClose: {
    display: "flex",
    alignItems: "center",
    height: 28,
    padding: "0 15px",
    marginLeft: 8,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 1,
    // background: theme.palette.app.navyRed, TODO::theme
    background: "red",
    color: "#fff",
    borderRadius: 14,
    border: "none",
    transition: "all 0.2s",
    cursor: "pointer",
    "&:hover": {
      background: "red",
      // background: theme.palette.app.red500,TODO::theme
    },
  },
  fileCloseIc: {
    marginRight: 5,
    fontSize: 16,
  },
  title: {
    paddingTop: "1em",
    color: "#345",
    [theme.breakpoints.down("xs")]: {
      paddingTop: 0,
      fontSize: 24,
    },
  },
  fileRemove: {
    marginLeft: 12,
    fontSize: 26,
    color: theme.palette.app.red400,
    cursor: "pointer",
    transition: "all 0.2s",
    "&:hover": {
      color: theme.palette.app.red500,
    },
  },
  fileSuccess: {
    color: "#8BC34A",
  },
  fileErrorsList: {
    paddingLeft: 16,
    "& span": {
      fontWeight: "bold",
    },
  },
}));

export default "styles";
